//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modules.UI.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string _Layout_cshtml_Execute_Administration {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string _Layout_cshtml_Execute_Projects {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string _Layout_cshtml_Execute_Reports {
            get {
                return ResourceManager.GetString("_Layout_cshtml_Execute_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: LDAP://contoso/DC=fabrikam,DC=com.
        /// </summary>
        public static string ActiveDirectorySettingsModel_RootGroupPath_ {
            get {
                return ResourceManager.GetString("ActiveDirectorySettingsModel_RootGroupPath_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root group.
        /// </summary>
        public static string ActiveDirectorySettingsModel_RootGroupPath_Root_group {
            get {
                return ResourceManager.GetString("ActiveDirectorySettingsModel_RootGroupPath_Root_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify Active Directory parent group.
        /// </summary>
        public static string ActiveDirectorySettingsModel_RootGroupPath_You_must_specify_Active_Directory_parent_group {
            get {
                return ResourceManager.GetString("ActiveDirectorySettingsModel_RootGroupPath_You_must_specify_Active_Directory_pare" +
                        "nt_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query name.
        /// </summary>
        public static string CreateQueryViewModel_Name_Query_name {
            get {
                return ResourceManager.GetString("CreateQueryViewModel_Name_Query_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string CreateQueryViewModel_ProjectId_Project {
            get {
                return ResourceManager.GetString("CreateQueryViewModel_ProjectId_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string CreateTaskViewModel_Repository_Repository {
            get {
                return ResourceManager.GetString("CreateTaskViewModel_Repository_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string.
        /// </summary>
        public static string DatabaseSettingsModel_ConnectionString_Connection_string {
            get {
                return ResourceManager.GetString("DatabaseSettingsModel_ConnectionString_Connection_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string to database.
        /// </summary>
        public static string DatabaseSettingsModel_ConnectionString_Connection_string_to_database {
            get {
                return ResourceManager.GetString("DatabaseSettingsModel_ConnectionString_Connection_string_to_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add block.
        /// </summary>
        public static string Edit_cshtml_Execute_Add_block {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Add_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Edit_cshtml_Execute_Comment {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor.
        /// </summary>
        public static string Edit_cshtml_Execute_Constructor {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user.
        /// </summary>
        public static string Edit_cshtml_Execute_Current_user {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Current_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query data source.
        /// </summary>
        public static string Edit_cshtml_Execute_Data_source {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Data_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit project.
        /// </summary>
        public static string Edit_cshtml_Execute_Edit_project {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Edit_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit query.
        /// </summary>
        public static string Edit_cshtml_Execute_Edit_query {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Edit_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter key.
        /// </summary>
        public static string Edit_cshtml_Execute_Parameter_key {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Parameter_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter value.
        /// </summary>
        public static string Edit_cshtml_Execute_Parameter_value {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Parameter_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string Edit_cshtml_Execute_Query {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query is used by system components. Any changes may occur troubles.
        /// </summary>
        public static string Edit_cshtml_Execute_Query_is_used_by_system_components {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Query_is_used_by_system_components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query name required.
        /// </summary>
        public static string Edit_cshtml_Execute_Query_name_required {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Query_name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query parameters.
        /// </summary>
        public static string Edit_cshtml_Execute_Query_parameters {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Query_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Edit_cshtml_Execute_Run {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Edit_cshtml_Execute_Save {
            get {
                return ResourceManager.GetString("Edit_cshtml_Execute_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Authorities.
        /// </summary>
        public static string EditProjectViewModel_Authorities_User_Authorities {
            get {
                return ResourceManager.GetString("EditProjectViewModel_Authorities_User_Authorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue tracker.
        /// </summary>
        public static string EditProjectViewModel_ItSettings_Issue_tracker {
            get {
                return ResourceManager.GetString("EditProjectViewModel_ItSettings_Issue_tracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string EditProjectViewModel_Notifications_Notifications {
            get {
                return ResourceManager.GetString("EditProjectViewModel_Notifications_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role.
        /// </summary>
        public static string EditProjectViewModel_ProjectRoles_User_role {
            get {
                return ResourceManager.GetString("EditProjectViewModel_ProjectRoles_User_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project settings.
        /// </summary>
        public static string EditProjectViewModel_ProjectSettings_Project_settings {
            get {
                return ResourceManager.GetString("EditProjectViewModel_ProjectSettings_Project_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access control.
        /// </summary>
        public static string EditProjectViewModel_RbacSettings_Access_control {
            get {
                return ResourceManager.GetString("EditProjectViewModel_RbacSettings_Access_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDL Rules.
        /// </summary>
        public static string EditProjectViewModel_SdlSettings_SDL_Rules {
            get {
                return ResourceManager.GetString("EditProjectViewModel_SdlSettings_SDL_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version control.
        /// </summary>
        public static string EditProjectViewModel_VcsSettings_Version_control {
            get {
                return ResourceManager.GetString("EditProjectViewModel_VcsSettings_Version_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: \\contoso\temp\sdl.
        /// </summary>
        public static string FileStorageSettingsModel_TempDirPath_For_example____contoso_temp_sdl {
            get {
                return ResourceManager.GetString("FileStorageSettingsModel_TempDirPath_For_example____contoso_temp_sdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp directory.
        /// </summary>
        public static string FileStorageSettingsModel_TempDirPath_Temp_directory {
            get {
                return ResourceManager.GetString("FileStorageSettingsModel_TempDirPath_Temp_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify file storage path.
        /// </summary>
        public static string FileStorageSettingsModel_TempDirPath_You_must_specify_file_storage_path {
            get {
                return ResourceManager.GetString("FileStorageSettingsModel_TempDirPath_You_must_specify_file_storage_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Get_cshtml_Execute_Description {
            get {
                return ResourceManager.GetString("Get_cshtml_Execute_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan task result.
        /// </summary>
        public static string Get_cshtml_Execute_Scan_task_result {
            get {
                return ResourceManager.GetString("Get_cshtml_Execute_Scan_task_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability info.
        /// </summary>
        public static string Get_cshtml_Execute_Vulnerability_info {
            get {
                return ResourceManager.GetString("Get_cshtml_Execute_Vulnerability_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability position.
        /// </summary>
        public static string Get_cshtml_Execute_Vulnerability_position {
            get {
                return ResourceManager.GetString("Get_cshtml_Execute_Vulnerability_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project scan tasks.
        /// </summary>
        public static string GetByProject_cshtml_Execute_Project_tasks {
            get {
                return ResourceManager.GetString("GetByProject_cshtml_Execute_Project_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new task.
        /// </summary>
        public static string GetByProject_cshtml_Execute_Start_new_task {
            get {
                return ResourceManager.GetString("GetByProject_cshtml_Execute_Start_new_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop task.
        /// </summary>
        public static string GetTaskResults_cshtml_Execute_Stop_task {
            get {
                return ResourceManager.GetString("GetTaskResults_cshtml_Execute_Stop_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan task results.
        /// </summary>
        public static string GetTaskResults_cshtml_Execute_TaskResults {
            get {
                return ResourceManager.GetString("GetTaskResults_cshtml_Execute_TaskResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HeaderActions_cshtml_Execute_About {
            get {
                return ResourceManager.GetString("HeaderActions_cshtml_Execute_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries.
        /// </summary>
        public static string HeaderActions_cshtml_Execute_Queries {
            get {
                return ResourceManager.GetString("HeaderActions_cshtml_Execute_Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Index_cshtml_Execute_Close {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new project.
        /// </summary>
        public static string Index_cshtml_Execute_Create_new_project {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Create_new_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to save changes?.
        /// </summary>
        public static string Index_cshtml_Execute_Do_you_really_want_to_save_changes_ {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Do_you_really_want_to_save_changes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Index_cshtml_Execute_Edit {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects list.
        /// </summary>
        public static string Index_cshtml_Execute_Projects {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Index_cshtml_Execute_Reports {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Index_cshtml_Execute_Save {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Index_cshtml_Execute_View {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Index_cshtml_Execute_Warning {
            get {
                return ResourceManager.GetString("Index_cshtml_Execute_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query storage.
        /// </summary>
        public static string List_cshtml_Execute_Query_storage {
            get {
                return ResourceManager.GetString("List_cshtml_Execute_Query_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string NewProjectViewModel_Alias_Alias {
            get {
                return ResourceManager.GetString("NewProjectViewModel_Alias_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only digits and characters.
        /// </summary>
        public static string NewProjectViewModel_Alias_Digits_and_characters_only {
            get {
                return ResourceManager.GetString("NewProjectViewModel_Alias_Digits_and_characters_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default branch.
        /// </summary>
        public static string NewProjectViewModel_DefaultBranchName_Default_branch {
            get {
                return ResourceManager.GetString("NewProjectViewModel_DefaultBranchName_Default_branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string NewProjectViewModel_DisplayName_Display_name {
            get {
                return ResourceManager.GetString("NewProjectViewModel_DisplayName_Display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository is not configured properly or not initialized.
        /// </summary>
        public static string NewTask_cshtml_ProjectIsNotConfigured {
            get {
                return ResourceManager.GetString("NewTask_cshtml_ProjectIsNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL enabled.
        /// </summary>
        public static string NotificationSettingsModel_IsSslEnabled_SSL_enabled {
            get {
                return ResourceManager.GetString("NotificationSettingsModel_IsSslEnabled_SSL_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main box name.
        /// </summary>
        public static string NotificationSettingsModel_MailBox_Main_box_name {
            get {
                return ResourceManager.GetString("NotificationSettingsModel_MailBox_Main_box_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main server host.
        /// </summary>
        public static string NotificationSettingsModel_MailServerHost_Main_server_host {
            get {
                return ResourceManager.GetString("NotificationSettingsModel_MailServerHost_Main_server_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main server port.
        /// </summary>
        public static string NotificationSettingsModel_MainServerPort_Main_server_port {
            get {
                return ResourceManager.GetString("NotificationSettingsModel_MainServerPort_Main_server_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string NotificationSettingsModel_Password_Password {
            get {
                return ResourceManager.GetString("NotificationSettingsModel_Password_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string NotificationSettingsModel_UserName_User_name {
            get {
                return ResourceManager.GetString("NotificationSettingsModel_UserName_User_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal cabinet.
        /// </summary>
        public static string PersonalCabinet_cshtml_Execute_Personal_cabinet {
            get {
                return ResourceManager.GetString("PersonalCabinet_cshtml_Execute_Personal_cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin name.
        /// </summary>
        public static string PluginSettingsModel_PluginName_Plugin_name {
            get {
                return ResourceManager.GetString("PluginSettingsModel_PluginName_Plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins list.
        /// </summary>
        public static string PluginSettingsModel_Plugins_Plugins_list {
            get {
                return ResourceManager.GetString("PluginSettingsModel_Plugins_Plugins_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string PluginSettingsModel_Settings_Settings {
            get {
                return ResourceManager.GetString("PluginSettingsModel_Settings_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.
        /// </summary>
        public static string ProjectItSettingsModel_PluginId_Plugin {
            get {
                return ResourceManager.GetString("ProjectItSettingsModel_PluginId_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProjectModel_Description_Description {
            get {
                return ResourceManager.GetString("ProjectModel_Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProjectModel_Name_Name {
            get {
                return ResourceManager.GetString("ProjectModel_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan core.
        /// </summary>
        public static string ProjectModel_ScanCore_Scan_core {
            get {
                return ResourceManager.GetString("ProjectModel_ScanCore_Scan_core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDL Policy.
        /// </summary>
        public static string ProjectModel_SdlPolicyStatus_SDL_Policy {
            get {
                return ResourceManager.GetString("ProjectModel_SdlPolicyStatus_SDL_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string ProjectNotificationSettingsModel_NotificationRules_Notifications {
            get {
                return ResourceManager.GetString("ProjectNotificationSettingsModel_NotificationRules_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Query.
        /// </summary>
        public static string ProjectNotificationSettingsModel_Query_Query {
            get {
                return ResourceManager.GetString("ProjectNotificationSettingsModel_Query_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no data to show.
        /// </summary>
        public static string ProjectPluginsModel_cshtml_Execute_There_are_no_data_to_show {
            get {
                return ResourceManager.GetString("ProjectPluginsModel_cshtml_Execute_There_are_no_data_to_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.
        /// </summary>
        public static string ProjectPluginsModel_Plugin_Plugin {
            get {
                return ResourceManager.GetString("ProjectPluginsModel_Plugin_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectPluginsModel_Project_Project {
            get {
                return ResourceManager.GetString("ProjectPluginsModel_Project_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDL Query.
        /// </summary>
        public static string ProjectSdlSettingsModel_Query_Query {
            get {
                return ResourceManager.GetString("ProjectSdlSettingsModel_Query_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDL rules.
        /// </summary>
        public static string ProjectSdlSettingsModel_SdlRules_SDL_rules {
            get {
                return ResourceManager.GetString("ProjectSdlSettingsModel_SdlRules_SDL_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string ProjectSettingsModel_Alias_Alias {
            get {
                return ResourceManager.GetString("ProjectSettingsModel_Alias_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only characters and numbers.
        /// </summary>
        public static string ProjectSettingsModel_Alias_Only_characters_and_numbers {
            get {
                return ResourceManager.GetString("ProjectSettingsModel_Alias_Only_characters_and_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create issues.
        /// </summary>
        public static string ProjectSettingsModel_CommitToIt_Create_issues {
            get {
                return ResourceManager.GetString("ProjectSettingsModel_CommitToIt_Create_issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit vulnerabilities.
        /// </summary>
        public static string ProjectSettingsModel_CommitToVcs_Commit_vulnerabilities {
            get {
                return ResourceManager.GetString("ProjectSettingsModel_CommitToVcs_Commit_vulnerabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default branch name.
        /// </summary>
        public static string ProjectSettingsModel_DefaultBranchName_Default_branch_name {
            get {
                return ResourceManager.GetString("ProjectSettingsModel_DefaultBranchName_Default_branch_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProjectSettingsModel_Description_Description {
            get {
                return ResourceManager.GetString("ProjectSettingsModel_Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string ProjectSettingsModel_DisplayName_Display_name {
            get {
                return ResourceManager.GetString("ProjectSettingsModel_DisplayName_Display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable polling.
        /// </summary>
        public static string ProjectSettingsModel_EnablePoll {
            get {
                return ResourceManager.GetString("ProjectSettingsModel_EnablePoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling timeout.
        /// </summary>
        public static string ProjectSettingsModel_PollTimeout {
            get {
                return ResourceManager.GetString("ProjectSettingsModel_PollTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCS sync enabled.
        /// </summary>
        public static string ProjectSettingsModel_VcsSyncEnabled_VCS_sync_enabled {
            get {
                return ResourceManager.GetString("ProjectSettingsModel_VcsSyncEnabled_VCS_sync_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT plugin.
        /// </summary>
        public static string ProjectTasksViewModel_ItPlugin_IT_plugin {
            get {
                return ResourceManager.GetString("ProjectTasksViewModel_ItPlugin_IT_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCS plugin.
        /// </summary>
        public static string ProjectTasksViewModel_VcsPlugin_VCS_plugin {
            get {
                return ResourceManager.GetString("ProjectTasksViewModel_VcsPlugin_VCS_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.
        /// </summary>
        public static string ProjectVcsSettingsModel_PluginId_Plugin {
            get {
                return ResourceManager.GetString("ProjectVcsSettingsModel_PluginId_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan project health.
        /// </summary>
        public static string ProjectViewModel_HealthTable_Health {
            get {
                return ResourceManager.GetString("ProjectViewModel_HealthTable_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan task  metrics.
        /// </summary>
        public static string ProjectViewModel_MetricsTable_Metrics {
            get {
                return ResourceManager.GetString("ProjectViewModel_MetricsTable_Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerabilities.
        /// </summary>
        public static string ProjectViewModel_VulnerabilityTable_Vulnerabilities {
            get {
                return ResourceManager.GetString("ProjectViewModel_VulnerabilityTable_Vulnerabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string QueryModel_Name_Name {
            get {
                return ResourceManager.GetString("QueryModel_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string QueryModel_Privacy_Privacy {
            get {
                return ResourceManager.GetString("QueryModel_Privacy_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ReportModel_Created_Created {
            get {
                return ResourceManager.GetString("ReportModel_Created_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string ReportModel_CreatedBy_Created_by {
            get {
                return ResourceManager.GetString("ReportModel_CreatedBy_Created_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ReportModel_Description_Description {
            get {
                return ResourceManager.GetString("ReportModel_Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ReportModel_Id_Id {
            get {
                return ResourceManager.GetString("ReportModel_Id_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string ReportModel_Modified_Modified {
            get {
                return ResourceManager.GetString("ReportModel_Modified_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified by.
        /// </summary>
        public static string ReportModel_ModifiedBy_Modified_by {
            get {
                return ResourceManager.GetString("ReportModel_ModifiedBy_Modified_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ReportModel_Name_Name {
            get {
                return ResourceManager.GetString("ReportModel_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ReportModel_ProjectName_Project {
            get {
                return ResourceManager.GetString("ReportModel_ProjectName_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan agents list.
        /// </summary>
        public static string ScanAgentSettingsModel_ScanAgents_Scan_agents {
            get {
                return ResourceManager.GetString("ScanAgentSettingsModel_ScanAgents_Scan_agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan core.
        /// </summary>
        public static string ScanCoreModel_DisplayName_Scan_core {
            get {
                return ResourceManager.GetString("ScanCoreModel_DisplayName_Scan_core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string SdlPolicyStatusModel_Error {
            get {
                return ResourceManager.GetString("SdlPolicyStatusModel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string SdlPolicyStatusModel_Failed_Failed {
            get {
                return ResourceManager.GetString("SdlPolicyStatusModel_Failed_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SdlPolicyStatusModel_Success_Success {
            get {
                return ResourceManager.GetString("SdlPolicyStatusModel_Success_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string SdlPolicyStatusModel_Unknown_Unknown {
            get {
                return ResourceManager.GetString("SdlPolicyStatusModel_Unknown_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory.
        /// </summary>
        public static string SettingsModel_ActiveDirectorySettings_Active_Directory {
            get {
                return ResourceManager.GetString("SettingsModel_ActiveDirectorySettings_Active_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SettingsModel_DatabaseSettings_Summary {
            get {
                return ResourceManager.GetString("SettingsModel_DatabaseSettings_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File storage.
        /// </summary>
        public static string SettingsModel_FileStorageSettings_File_storage {
            get {
                return ResourceManager.GetString("SettingsModel_FileStorageSettings_File_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string SettingsModel_NotificationSettings_Notifications {
            get {
                return ResourceManager.GetString("SettingsModel_NotificationSettings_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string SettingsModel_PluginSettings_Plugins {
            get {
                return ResourceManager.GetString("SettingsModel_PluginSettings_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan agents.
        /// </summary>
        public static string SettingsModel_ScanAgentSettings_Scan_agents {
            get {
                return ResourceManager.GetString("SettingsModel_ScanAgentSettings_Scan_agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Show_cshtml_Execute_Report {
            get {
                return ResourceManager.GetString("Show_cshtml_Execute_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence description.
        /// </summary>
        public static string SummarySettingsModel_LicenceDescription_Licence_description {
            get {
                return ResourceManager.GetString("SummarySettingsModel_LicenceDescription_Licence_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Id.
        /// </summary>
        public static string SummarySettingsModel_LicenceId_Licence_Id {
            get {
                return ResourceManager.GetString("SummarySettingsModel_LicenceId_Licence_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no data to show.
        /// </summary>
        public static string TableRenderView_cshtml_Execute_NoDataToShow {
            get {
                return ResourceManager.GetString("TableRenderView_cshtml_Execute_NoDataToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzed Lines.
        /// </summary>
        public static string TaskModel_AnalyzedLinesCount_Analyzed_Lines {
            get {
                return ResourceManager.GetString("TaskModel_AnalyzedLinesCount_Analyzed_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzed Size (Kb).
        /// </summary>
        public static string TaskModel_AnalyzedSizeKb_Analyzed_Size__Kb_ {
            get {
                return ResourceManager.GetString("TaskModel_AnalyzedSizeKb_Analyzed_Size__Kb_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string TaskModel_Created_Created {
            get {
                return ResourceManager.GetString("TaskModel_Created_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string TaskModel_CreatedBy_Created_by {
            get {
                return ResourceManager.GetString("TaskModel_CreatedBy_Created_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string TaskModel_Finished_Finished {
            get {
                return ResourceManager.GetString("TaskModel_Finished_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder path.
        /// </summary>
        public static string TaskModel_FolderPath_Folder_path {
            get {
                return ResourceManager.GetString("TaskModel_FolderPath_Folder_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder size (KB).
        /// </summary>
        public static string TaskModel_FolderSizeKb_Folder_size__KB_ {
            get {
                return ResourceManager.GetString("TaskModel_FolderSizeKb_Folder_size__KB_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string TaskModel_Repository_Repository {
            get {
                return ResourceManager.GetString("TaskModel_Repository_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan core.
        /// </summary>
        public static string TaskModel_ScanCore_Scan_core {
            get {
                return ResourceManager.GetString("TaskModel_ScanCore_Scan_core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan core working time (s).
        /// </summary>
        public static string TaskModel_ScanCoreWorkingTimeSec_Scan_core_working_time__s_ {
            get {
                return ResourceManager.GetString("TaskModel_ScanCoreWorkingTimeSec_Scan_core_working_time__s_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TaskModel_Status_Ststus {
            get {
                return ResourceManager.GetString("TaskModel_Status_Ststus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional exploit conditions.
        /// </summary>
        public static string TaskResultModel_AdditionalExploitConditions_Additional_exploit_conditions {
            get {
                return ResourceManager.GetString("TaskResultModel_AdditionalExploitConditions_Additional_exploit_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TaskResultModel_Description_Description {
            get {
                return ResourceManager.GetString("TaskResultModel_Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploit graph.
        /// </summary>
        public static string TaskResultModel_ExploitGraph_Exploit_graph {
            get {
                return ResourceManager.GetString("TaskResultModel_ExploitGraph_Exploit_graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string TaskResultModel_File_File_name {
            get {
                return ResourceManager.GetString("TaskResultModel_File_File_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function name.
        /// </summary>
        public static string TaskResultModel_Function_Function_name {
            get {
                return ResourceManager.GetString("TaskResultModel_Function_Function_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue number.
        /// </summary>
        public static string TaskResultModel_IssueNumber_Issue_number {
            get {
                return ResourceManager.GetString("TaskResultModel_IssueNumber_Issue_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue link.
        /// </summary>
        public static string TaskResultModel_IssueUrl_Issue_link {
            get {
                return ResourceManager.GetString("TaskResultModel_IssueUrl_Issue_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number.
        /// </summary>
        public static string TaskResultModel_LineNumber_Line_number {
            get {
                return ResourceManager.GetString("TaskResultModel_LineNumber_Line_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position number.
        /// </summary>
        public static string TaskResultModel_LinePosition_Position_number {
            get {
                return ResourceManager.GetString("TaskResultModel_LinePosition_Position_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string TaskResultModel_Message_Message {
            get {
                return ResourceManager.GetString("TaskResultModel_Message_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity type.
        /// </summary>
        public static string TaskResultModel_SeverityType_Severity_type {
            get {
                return ResourceManager.GetString("TaskResultModel_SeverityType_Severity_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Id.
        /// </summary>
        public static string TaskResultModel_TaskId_Task_Id {
            get {
                return ResourceManager.GetString("TaskResultModel_TaskId_Task_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability type.
        /// </summary>
        public static string TaskResultModel_Type_Vulnerability_type {
            get {
                return ResourceManager.GetString("TaskResultModel_Type_Vulnerability_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability type short.
        /// </summary>
        public static string TaskResultModel_TypeShort_Vulnerability_type_short {
            get {
                return ResourceManager.GetString("TaskResultModel_TypeShort_Vulnerability_type_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT plugin.
        /// </summary>
        public static string TaskResultsViewModel_ItPlugin_IT_plugin {
            get {
                return ResourceManager.GetString("TaskResultsViewModel_ItPlugin_IT_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCS plugin.
        /// </summary>
        public static string TaskResultsViewModel_VcsPlugin_VCS_plugin {
            get {
                return ResourceManager.GetString("TaskResultsViewModel_VcsPlugin_VCS_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task done.
        /// </summary>
        public static string TaskStatusModel_Done_Task_done {
            get {
                return ResourceManager.GetString("TaskStatusModel_Done_Task_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        public static string TaskStatusModel_New_New_task {
            get {
                return ResourceManager.GetString("TaskStatusModel_New_New_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post processing.
        /// </summary>
        public static string TaskStatusModel_PostProcessing_Post_processing {
            get {
                return ResourceManager.GetString("TaskStatusModel_PostProcessing_Post_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre processing.
        /// </summary>
        public static string TaskStatusModel_PreProcessing_Pre_processing {
            get {
                return ResourceManager.GetString("TaskStatusModel_PreProcessing_Pre_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to postprocessing.
        /// </summary>
        public static string TaskStatusModel_ReadyToPostProcessing {
            get {
                return ResourceManager.GetString("TaskStatusModel_ReadyToPostProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to scan.
        /// </summary>
        public static string TaskStatusModel_ReadyToStan_Ready_to_scan {
            get {
                return ResourceManager.GetString("TaskStatusModel_ReadyToStan_Ready_to_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        public static string TaskStatusModel_Scanning_Scanning {
            get {
                return ResourceManager.GetString("TaskStatusModel_Scanning_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string UserModel_DisplayName_Display_name {
            get {
                return ResourceManager.GetString("UserModel_DisplayName_Display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string UserModel_Email_Email {
            get {
                return ResourceManager.GetString("UserModel_Email_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string UserModel_Login_Login {
            get {
                return ResourceManager.GetString("UserModel_Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SID.
        /// </summary>
        public static string UserModel_Sid_SID {
            get {
                return ResourceManager.GetString("UserModel_Sid_SID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Tracker.
        /// </summary>
        public static string UserSettingsModel_ItPluginSettings_Issue_Tracker {
            get {
                return ResourceManager.GetString("UserSettingsModel_ItPluginSettings_Issue_Tracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version control.
        /// </summary>
        public static string UserSettingsModel_VcsPluginSettings_Version_control {
            get {
                return ResourceManager.GetString("UserSettingsModel_VcsPluginSettings_Version_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User info.
        /// </summary>
        public static string UserSettingsViewModel_UserInfo_User_info {
            get {
                return ResourceManager.GetString("UserSettingsViewModel_UserInfo_User_info", resourceCulture);
            }
        }
    }
}
