//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modules.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request method is not specified.
        /// </summary>
        internal static string ApiService_Handle_RequestMethodNotSpecified {
            get {
                return ResourceManager.GetString("ApiService_Handle_RequestMethodNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source type is not specified.
        /// </summary>
        internal static string ApiService_Handle_SourceTypeNotSpecified {
            get {
                return ResourceManager.GetString("ApiService_Handle_SourceTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Enum_QueryPrivacyType_Private {
            get {
                return ResourceManager.GetString("Enum_QueryPrivacyType_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public on read.
        /// </summary>
        internal static string Enum_QueryPrivacyType_PublicRead {
            get {
                return ResourceManager.GetString("Enum_QueryPrivacyType_PublicRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public on write.
        /// </summary>
        internal static string Enum_QueryPrivacyType_PublicWrite {
            get {
                return ResourceManager.GetString("Enum_QueryPrivacyType_PublicWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Enum_SortOrder_Ascending {
            get {
                return ResourceManager.GetString("Enum_SortOrder_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Enum_SortOrder_Descending {
            get {
                return ResourceManager.GetString("Enum_SortOrder_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        internal static string Enum_SortOrder_Unspecified {
            get {
                return ResourceManager.GetString("Enum_SortOrder_Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting value should be less than {0}..
        /// </summary>
        internal static string MinValidationSettingError {
            get {
                return ResourceManager.GetString("MinValidationSettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzed [KB].
        /// </summary>
        internal static string Property_AnalyzedSize {
            get {
                return ResourceManager.GetString("Property_AnalyzedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Property_Branch {
            get {
                return ResourceManager.GetString("Property_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of code.
        /// </summary>
        internal static string Property_CodeLines {
            get {
                return ResourceManager.GetString("Property_CodeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Property_Count {
            get {
                return ResourceManager.GetString("Property_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Property_Created {
            get {
                return ResourceManager.GetString("Property_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string Property_Creator {
            get {
                return ResourceManager.GetString("Property_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Time.
        /// </summary>
        internal static string Property_ExecutionTime {
            get {
                return ResourceManager.GetString("Property_ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploit.
        /// </summary>
        internal static string Property_Exploit {
            get {
                return ResourceManager.GetString("Property_Exploit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        internal static string Property_ExploitConditions {
            get {
                return ResourceManager.GetString("Property_ExploitConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Property_File {
            get {
                return ResourceManager.GetString("Property_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Property_Finished {
            get {
                return ResourceManager.GetString("Property_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string Property_Fixed {
            get {
                return ResourceManager.GetString("Property_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp folder path.
        /// </summary>
        internal static string Property_FolderPath {
            get {
                return ResourceManager.GetString("Property_FolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder [KB].
        /// </summary>
        internal static string Property_FolderSize {
            get {
                return ResourceManager.GetString("Property_FolderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FP.
        /// </summary>
        internal static string Property_FP {
            get {
                return ResourceManager.GetString("Property_FP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string Property_Function {
            get {
                return ResourceManager.GetString("Property_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string Property_High {
            get {
                return ResourceManager.GetString("Property_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixedΔ.
        /// </summary>
        internal static string Property_IncrementFixed {
            get {
                return ResourceManager.GetString("Property_IncrementFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPΔ.
        /// </summary>
        internal static string Property_IncrementFP {
            get {
                return ResourceManager.GetString("Property_IncrementFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReopenΔ.
        /// </summary>
        internal static string Property_IncrementReopen {
            get {
                return ResourceManager.GetString("Property_IncrementReopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TodoΔ.
        /// </summary>
        internal static string Property_IncrementTodo {
            get {
                return ResourceManager.GetString("Property_IncrementTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string Property_IssueLink {
            get {
                return ResourceManager.GetString("Property_IssueLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Number.
        /// </summary>
        internal static string Property_IssueNumber {
            get {
                return ResourceManager.GetString("Property_IssueNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number.
        /// </summary>
        internal static string Property_LineNumber {
            get {
                return ResourceManager.GetString("Property_LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position in line.
        /// </summary>
        internal static string Property_LinePosition {
            get {
                return ResourceManager.GetString("Property_LinePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string Property_LinesCount {
            get {
                return ResourceManager.GetString("Property_LinesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Property_Low {
            get {
                return ResourceManager.GetString("Property_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name.
        /// </summary>
        internal static string Property_Machine {
            get {
                return ResourceManager.GetString("Property_Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Property_Medium {
            get {
                return ResourceManager.GetString("Property_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Property_Name {
            get {
                return ResourceManager.GetString("Property_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Line.
        /// </summary>
        internal static string Property_RawLine {
            get {
                return ResourceManager.GetString("Property_RawLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen.
        /// </summary>
        internal static string Property_Reopen {
            get {
                return ResourceManager.GetString("Property_Reopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Property_Repository {
            get {
                return ResourceManager.GetString("Property_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Work Time.
        /// </summary>
        internal static string Property_SC_Work_Time {
            get {
                return ResourceManager.GetString("Property_SC_Work_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan core type.
        /// </summary>
        internal static string Property_ScanCore {
            get {
                return ResourceManager.GetString("Property_ScanCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDL policy.
        /// </summary>
        internal static string Property_SdlPolicyStatus {
            get {
                return ResourceManager.GetString("Property_SdlPolicyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string Property_Severity {
            get {
                return ResourceManager.GetString("Property_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed [KB/s].
        /// </summary>
        internal static string Property_Speed {
            get {
                return ResourceManager.GetString("Property_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Property_Status {
            get {
                return ResourceManager.GetString("Property_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time [s].
        /// </summary>
        internal static string Property_Time {
            get {
                return ResourceManager.GetString("Property_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo.
        /// </summary>
        internal static string Property_Todo {
            get {
                return ResourceManager.GetString("Property_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Property_Type {
            get {
                return ResourceManager.GetString("Property_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Property_Version {
            get {
                return ResourceManager.GetString("Property_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability.
        /// </summary>
        internal static string Property_Vulnerability {
            get {
                return ResourceManager.GetString("Property_Vulnerability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This condition is unsupported for this setting..
        /// </summary>
        internal static string UnsupportedConditionSetting {
            get {
                return ResourceManager.GetString("UnsupportedConditionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while validation setting value..
        /// </summary>
        internal static string ValidationErrorOccurredSetting {
            get {
                return ResourceManager.GetString("ValidationErrorOccurredSetting", resourceCulture);
            }
        }
    }
}
