//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workflow.GitHub.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Workflow.GitHub.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation state can&apos;t be changed from {0} to {1}..
        /// </summary>
        internal static string AnnotationStateCantBeChanged {
            get {
                return ResourceManager.GetString("AnnotationStateCantBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FP.
        /// </summary>
        internal static string FalsePositiveMarker {
            get {
                return ResourceManager.GetString("FalsePositiveMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIXED.
        /// </summary>
        internal static string FixedMarker {
            get {
                return ResourceManager.GetString("FixedMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong marker found: {0}.
        /// </summary>
        internal static string IssueAnnotationSerializer_Deserialize_Wrong_marker_found {
            get {
                return ResourceManager.GetString("IssueAnnotationSerializer_Deserialize_Wrong_marker_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Issue: {0}.
        /// </summary>
        internal static string IssueNameFormat {
            get {
                return ResourceManager.GetString("IssueNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : {0} left.
        /// </summary>
        internal static string IssueNameLeft {
            get {
                return ResourceManager.GetString("IssueNameLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REOPEN.
        /// </summary>
        internal static string ReopenMarker {
            get {
                return ResourceManager.GetString("ReopenMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string TodoMarker {
            get {
                return ResourceManager.GetString("TodoMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFY.
        /// </summary>
        internal static string VerifyMarker {
            get {
                return ResourceManager.GetString("VerifyMarker", resourceCulture);
            }
        }
    }
}
