//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationRules
    {
        public long Id { get; set; }
        public long ProjectId { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public string Query { get; set; }
        public System.DateTime Added { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
