//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Queries()
        {
            this.Roles = new HashSet<Roles>();
            this.Roles1 = new HashSet<Roles>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public int Visibility { get; set; }
        public int Privacy { get; set; }
        public Nullable<long> TargetCultureId { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public long CreatedById { get; set; }
        public System.DateTime CreatedUtc { get; set; }
        public long ModifiedById { get; set; }
        public System.DateTime ModifiedUtc { get; set; }
        public string Query { get; set; }
        public string JsonQuery { get; set; }
        public bool IsSystem { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roles> Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roles> Roles1 { get; set; }
        public virtual Cultures Cultures { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
