//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public long Id { get; set; }
        public string Type { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<System.DateTime> Processed { get; set; }
        public string Body { get; set; }
    }
}
