//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public long Id { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string DisplayName { get; set; }
        public System.DateTime Created { get; set; }
        public long CreatedById { get; set; }
        public System.DateTime Modified { get; set; }
        public long ModifiedById { get; set; }
        public string Description { get; set; }
        public string Rule { get; set; }
        public bool IsSystem { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
