//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleAuthorities
    {
        public long Id { get; set; }
        public long RoleId { get; set; }
        public long AuthorityId { get; set; }
    
        public virtual Authorities Authorities { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
