//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Roles()
        {
            this.RoleAuthorities = new HashSet<RoleAuthorities>();
            this.UserProjectSettings = new HashSet<UserProjectSettings>();
        }
    
        public long Id { get; set; }
        public string Sid { get; set; }
        public string Alias { get; set; }
        public string DisplayName { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public long TasksQueryId { get; set; }
        public long TaskResultsQueryId { get; set; }
    
        public virtual Queries Queries { get; set; }
        public virtual Queries Queries1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleAuthorities> RoleAuthorities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProjectSettings> UserProjectSettings { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
