//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Settings()
        {
            this.Settings1 = new HashSet<Settings>();
            this.SettingValues = new HashSet<SettingValues>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string DisplayName { get; set; }
        public Nullable<long> SettingGroupId { get; set; }
        public int SettingType { get; set; }
        public int SettingOwner { get; set; }
        public Nullable<long> ParentSettingId { get; set; }
        public string DefaultValue { get; set; }
        public string ParentSettingItemKey { get; set; }
        public string Conditions { get; set; }
        public Nullable<long> OwnerPluginId { get; set; }
        public bool IsAuth { get; set; }
        public bool IsArchived { get; set; }
    
        public virtual SettingGroups SettingGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Settings> Settings1 { get; set; }
        public virtual Settings Settings2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SettingValues> SettingValues { get; set; }
        public virtual Plugins Plugins { get; set; }
    }
}
