//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SettingGroups()
        {
            this.SettingGroups1 = new HashSet<SettingGroups>();
            this.Settings = new HashSet<Settings>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string DisplayName { get; set; }
        public Nullable<long> ParentGroupId { get; set; }
        public Nullable<long> OwnerPluginId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SettingGroups> SettingGroups1 { get; set; }
        public virtual SettingGroups SettingGroups2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Settings> Settings { get; set; }
        public virtual Plugins Plugins { get; set; }
    }
}
