//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagEntities
    {
        public long Id { get; set; }
        public long TagId { get; set; }
        public long TableId { get; set; }
        public long EntityId { get; set; }
    
        public virtual Tables Tables { get; set; }
        public virtual Tags Tags { get; set; }
    }
}
