//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskResults
    {
        public long Id { get; set; }
        public long TaskId { get; set; }
        public string Message { get; set; }
        public string ExploitGraph { get; set; }
        public string AdditionalExploitConditions { get; set; }
        public string File { get; set; }
        public string Function { get; set; }
        public int LineNumber { get; set; }
        public string Place { get; set; }
        public string SourceFile { get; set; }
        public string RawLine { get; set; }
        public string Type { get; set; }
        public string TypeShort { get; set; }
        public string Description { get; set; }
        public int SeverityType { get; set; }
        public int LinePosition { get; set; }
        public string IssueNumber { get; set; }
        public string IssueUrl { get; set; }
    
        public virtual Tasks Tasks { get; set; }
    }
}
