//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks()
        {
            this.TaskResults = new HashSet<TaskResults>();
        }
    
        public long Id { get; set; }
        public long ProjectId { get; set; }
        public System.DateTime Created { get; set; }
        public long CreatedById { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
        public System.DateTime Modified { get; set; }
        public long ModifiedById { get; set; }
        public string Repository { get; set; }
        public int Status { get; set; }
        public int SdlStatus { get; set; }
        public string FolderPath { get; set; }
        public string LogPath { get; set; }
        public string ResultPath { get; set; }
        public Nullable<long> FolderSize { get; set; }
        public Nullable<long> ScanCoreWorkingTime { get; set; }
        public string AnalyzedFiles { get; set; }
        public Nullable<long> AnalyzedSize { get; set; }
        public Nullable<long> AnalyzedLinesCount { get; set; }
        public Nullable<int> LowSeverityVulns { get; set; }
        public Nullable<int> MediumSeverityVulns { get; set; }
        public Nullable<int> HighSeverityVulns { get; set; }
        public Nullable<int> FP { get; set; }
        public Nullable<int> Todo { get; set; }
        public Nullable<int> Reopen { get; set; }
        public Nullable<int> Fixed { get; set; }
        public Nullable<int> IncrementFP { get; set; }
        public Nullable<int> IncrementTodo { get; set; }
        public Nullable<int> IncrementReopen { get; set; }
        public Nullable<int> IncrementFixed { get; set; }
        public int Resolution { get; set; }
        public string ResolutionMessage { get; set; }
        public Nullable<long> AgentId { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual SdlStatuses SdlStatuses { get; set; }
        public virtual TaskResolutions TaskResolutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskResults> TaskResults { get; set; }
        public virtual TaskStatuses TaskStatuses { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual ScanAgents ScanAgents { get; set; }
    }
}
