//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInterfaces
    {
        public long Id { get; set; }
        public string Host { get; set; }
        public string RemoteIp { get; set; }
        public int RemotePort { get; set; }
        public string Version { get; set; }
        public System.DateTime RegisteredUtc { get; set; }
        public System.DateTime LastCheckedUtc { get; set; }
    }
}
