//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowRules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowRules()
        {
            this.WorkflowRuleToEvents = new HashSet<WorkflowRuleToEvents>();
        }
    
        public long Id { get; set; }
        public long ProjectId { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public string Query { get; set; }
        public bool IsEventTriggered { get; set; }
        public bool IsTimeTriggered { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<bool> IsRepeatable { get; set; }
        public string Repeat { get; set; }
        public System.DateTime Added { get; set; }
        public string ActionKey { get; set; }
        public bool IsForAllEvents { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowRuleToEvents> WorkflowRuleToEvents { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
