//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowRuleToEvents
    {
        public long Id { get; set; }
        public long WorkflowRuleId { get; set; }
        public long EventId { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual WorkflowRules WorkflowRules { get; set; }
    }
}
