//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbMigrations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbMigrations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0} in {1} table already exists..
        /// </summary>
        internal static string ColumnAlreadyExists {
            get {
                return ResourceManager.GetString("ColumnAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0} in {1} table doesn&apos;t exist..
        /// </summary>
        internal static string ColumnDoesntExist {
            get {
                return ResourceManager.GetString("ColumnDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint {0} in {1} table already exists..
        /// </summary>
        internal static string ConstraintAlreadyExists {
            get {
                return ResourceManager.GetString("ConstraintAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint {0} in {1} table doesn&apos;t exist..
        /// </summary>
        internal static string ConstraintDoesntExist {
            get {
                return ResourceManager.GetString("ConstraintDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is up to date already..
        /// </summary>
        internal static string DbIsUpToDate {
            get {
                return ResourceManager.GetString("DbIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying {0} migration from {1} version to {2} version..
        /// </summary>
        internal static string DbMigrator_MigrationApplying {
            get {
                return ResourceManager.GetString("DbMigrator_MigrationApplying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index can&apos;t be created by empty collection of columns..
        /// </summary>
        internal static string EmptyColumnsForIndex {
            get {
                return ResourceManager.GetString("EmptyColumnsForIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index {0} in {1} table already exists..
        /// </summary>
        internal static string IndexAlreadyExists {
            get {
                return ResourceManager.GetString("IndexAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index {0} in {1} table doesn&apos;t exist..
        /// </summary>
        internal static string IndexDoesntExist {
            get {
                return ResourceManager.GetString("IndexDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} migration from {1} version to {2} version is applied successfully..
        /// </summary>
        internal static string MigrationAppliedSuccessfully {
            get {
                return ResourceManager.GetString("MigrationAppliedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while applying migration {0} from {1} version to {2} version..
        /// </summary>
        internal static string MigrationError {
            get {
                return ResourceManager.GetString("MigrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} version corresponds to more than 1 migration. Migrations: {1}.
        /// </summary>
        internal static string MigrationVersionIsDuplicated {
            get {
                return ResourceManager.GetString("MigrationVersionIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key {0} already exists.
        /// </summary>
        internal static string PrimaryKeyAlreadyExists {
            get {
                return ResourceManager.GetString("PrimaryKeyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table {0} already exists..
        /// </summary>
        internal static string TableAlreadyExists {
            get {
                return ResourceManager.GetString("TableAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key is not specified for table {0}..
        /// </summary>
        internal static string TableDoesntContainPrimaryKey {
            get {
                return ResourceManager.GetString("TableDoesntContainPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table {0} doesn&apos;t exist..
        /// </summary>
        internal static string TableDoesntExist {
            get {
                return ResourceManager.GetString("TableDoesntExist", resourceCulture);
            }
        }
    }
}
