//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Scheduler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Scheduler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job created. JobType=&apos;{0}&apos;.
        /// </summary>
        internal static string ContainerJobFactory_NewJob_JobCreated {
            get {
                return ResourceManager.GetString("ContainerJobFactory_NewJob_JobCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler job container disposed. JobType=&apos;{0}&apos;.
        /// </summary>
        internal static string ContainerJobFactory_ReturnJob_ContainerDisposed {
            get {
                return ResourceManager.GetString("ContainerJobFactory_ReturnJob_ContainerDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.{0}.
        /// </summary>
        internal static string JobScheduler_Start_Job_Prefix {
            get {
                return ResourceManager.GetString("JobScheduler_Start_Job_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled job &apos;{0}&apos;.
        /// </summary>
        internal static string JobScheduler_Start_Scheduled_job {
            get {
                return ResourceManager.GetString("JobScheduler_Start_Scheduled_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler already started.
        /// </summary>
        internal static string JobScheduler_Start_Scheduler_already_started {
            get {
                return ResourceManager.GetString("JobScheduler_Start_Scheduler_already_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler started.
        /// </summary>
        internal static string JobScheduler_Start_Scheduler_started {
            get {
                return ResourceManager.GetString("JobScheduler_Start_Scheduler_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error throwen while scheduler stopping.
        /// </summary>
        internal static string JobScheduler_Stop_Error_throwen_while_scheduler_stopping {
            get {
                return ResourceManager.GetString("JobScheduler_Stop_Error_throwen_while_scheduler_stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler succesfully stopped.
        /// </summary>
        internal static string JobScheduler_Stop_Scheduler_succesfully_stopped {
            get {
                return ResourceManager.GetString("JobScheduler_Stop_Scheduler_succesfully_stopped", resourceCulture);
            }
        }
    }
}
