//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application configuration updated. Key=&apos;{0}&apos;, Value=&apos;{1}&apos;.
        /// </summary>
        internal static string ApplicationConfigurationProvider_SetConfig_ConfigurationUpdated {
            get {
                return ResourceManager.GetString("ApplicationConfigurationProvider_SetConfig_ConfigurationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}[{1}].
        /// </summary>
        internal static string CollectionElementName {
            get {
                return ResourceManager.GetString("CollectionElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Length.
        /// </summary>
        internal static string CollectionParameterLength {
            get {
                return ResourceManager.GetString("CollectionParameterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: {0}
        ///Message: {1}
        ///Stacktrace: {2}
        ///.
        /// </summary>
        internal static string ExceptionFormatString {
            get {
                return ResourceManager.GetString("ExceptionFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxExecutionTime=&apos;{0}&apos;ms, ElapsedTime=&apos;{1:F0}&apos;ms, Method=&apos;{2}&apos;.
        /// </summary>
        internal static string ExecutionTimeInfo {
            get {
                return ResourceManager.GetString("ExecutionTimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner exception:
        ///{0}
        ///.
        /// </summary>
        internal static string InnerExceptionFormatString {
            get {
                return ResourceManager.GetString("InnerExceptionFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}({2}).
        /// </summary>
        internal static string MethodSignature {
            get {
                return ResourceManager.GetString("MethodSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\r\n{1}.
        /// </summary>
        internal static string MethodWithParameters {
            get {
                return ResourceManager.GetString("MethodWithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module version is not supported.
        /// </summary>
        internal static string ModuleVersionIsNotSupportedException_ModuleVersionIsNotSupportedException_Module_version_is_not_supported {
            get {
                return ResourceManager.GetString("ModuleVersionIsNotSupportedException_ModuleVersionIsNotSupportedException_Module_" +
                        "version_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        internal static string NullValue {
            get {
                return ResourceManager.GetString("NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}.
        /// </summary>
        internal static string ParameterName {
            get {
                return ResourceManager.GetString("ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}={1}.
        /// </summary>
        internal static string ParameterNameValue {
            get {
                return ResourceManager.GetString("ParameterNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is not found in resources..
        /// </summary>
        internal static string ResourceFileNotFound {
            get {
                return ResourceManager.GetString("ResourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Value.
        /// </summary>
        internal static string ReturnValueName {
            get {
                return ResourceManager.GetString("ReturnValueName", resourceCulture);
            }
        }
    }
}
